FROM postgres:15.3
# RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/*
# Set up Your Language
# RUN localedef -i ja_JP -c -f UTF-8 -A /usr/share/locale/locale.alias ja_JP.UTF-8
# ENV TZ Asia/Tokyo
# ENV LANG ja_JP.UTF-8